In [14]:
a=[1,2,3,4]
b=[5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
a=[1,2,3,4]
b=[5,6,7,8]
[a[i]+b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [21]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [25]:
arr[:,:1]   #start_row:end_row,start_col:end_col

array([[1],
       [4],
       [7]])

In [26]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [27]:
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [28]:
arr[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [35]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [36]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [37]:
np.eye(3,3).astype(int).dtype

dtype('int32')

In [38]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.eye(3,3).astype(float).dtype

dtype('float64')

In [42]:
a[a>2]

array([3, 4])

In [43]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
#vector operations
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [51]:
a*2

array([2, 4, 6])

In [53]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [54]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [55]:
#Matrixx
array=([[1,2,3],
       [4,5,6],
       [7,8,9]])

In [57]:
a.T

array([[1, 3],
       [2, 4]])

In [58]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
np.linalg.det(a)

-2.0000000000000004

In [61]:
np.hstack((a,b)) # horizontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [62]:
np.vstack((a,b)) # vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
a=np.array([1,2,3,4,5,6,7,8,9,4,5,7])

In [65]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 7])

In [67]:
np.reshape(np.reshape(a,(3,4)),(2,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 4, 5, 7]])

In [68]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 4],
       [5, 7]])

In [69]:
np.reshape(a,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 5, 7]])

In [70]:
b=np.resize(a,(3,4))

In [71]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 5, 7]])

In [72]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([7, 8, 9, 4, 5, 7])]

In [73]:
#copy and view
arr=np.array([1,2,3,4,5,6])

In [74]:
b=arr.view()

In [75]:
b[0]=10

In [76]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [77]:
c=arr.copy()

In [78]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [79]:
c[0]=11

In [80]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))