In [78]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [79]:
iris=load_iris()

In [80]:
data=pd.DataFrame(iris.data,columns=iris.feature_names)
data["labels"]=iris.target

In [81]:
data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),labels
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [82]:
x=data.drop(columns='labels')
y=data.labels


In [83]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [84]:
model=SVC()

In [85]:
params={"C":[0.1,1,10,100],
       "kernel":["linear","poly","rbf"],
       "gamma":["auto", "scale"]}

In [86]:
grid_search = GridSearchCV(
    estimator = model,
    param_grid = params,
    scoring="accuracy",
    cv = 5,
   verbose=3
)

In [87]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END ..C=0.1, gamma=auto, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.917 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.833 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=auto, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.958 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.958 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.958 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.833 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.958 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=auto, kernel=poly;, score=1.000 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=auto, kernel=rbf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'poly', 'rbf']},
             scoring='accuracy', verbose=3)

In [93]:
best_model = grid_search.best_estimator_

In [94]:
grid_search.best_params_

{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}

In [95]:
grid_search.best_score_

0.9583333333333334

In [96]:
pred = best_model.predict(x_test)

In [97]:
accuracy_score(y_test , pred)

1.0

In [99]:
print(confusion_matrix(y_test, pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [100]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

